# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 04:12
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import sophia.models


class Migration(migrations.Migration):

    dependencies = [
        ('sophia', '0004_auto_20160602_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', sophia.models.SmartImageField(blank=True, help_text=b'For best results, the width of the image                                                 should be larger than the height. Ideally                                                 5:3 aspect ratio', null=True, upload_to=b'./blog_main_images/')),
                ('title', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='sophia.BlogTag'),
        ),
    ]
