# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sophia', '0005_auto_20160621_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='start_date',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='end_year',
            field=models.DateField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='start_year',
            field=models.CharField(default=2016, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=models.TextField(),
        ),
    ]
