# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sophia', '0006_auto_20160728_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='end_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
