# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 04:00
from __future__ import unicode_literals

from django.db import migrations


DAYS_OF_WEEK = {
    'Monday': '1',
    'Tuesday': '2',
    'Wednesday': '3',
    'Thursday': '4',
    'Friday': '5',
    'Saturday': '6',
    'Sunday': '7',
}

def update_timeslot_days(apps, schema_editor):
    Timeslot = apps.get_model('sophia', 'Timeslot')
    for ts in Timeslot.objects.all():
        new_value = DAYS_OF_WEEK.get(ts.day)
        if not new_value:
            continue
        ts.day = new_value
        ts.save()

class Migration(migrations.Migration):

    dependencies = [
        ('sophia', '0007_auto_20160728_2201'),
    ]

    operations = [
        migrations.RunPython(update_timeslot_days)
    ]
