# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-16 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sophia', '0009_fix_day_index_on_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=47)),
                ('last_name', models.CharField(max_length=47)),
                ('contact_email', models.EmailField(max_length=75)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day', models.CharField(choices=[(b'0', b'Monday'), (b'1', b'Tuesday'), (b'2', b'Wednesday'), (b'3', b'Thursday'), (b'4', b'Friday'), (b'5', b'Saturday'), (b'6', b'Sunday')], max_length=9)),
                ('period', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('is_trial', models.BooleanField(default=False)),
                ('is_held', models.BooleanField(default=False)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='scheduledlesson',
            name='timeslot',
        ),
        migrations.AddField(
            model_name='scheduledlesson',
            name='cancelled_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledlesson',
            name='completed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledlesson',
            name='rescheduled_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(to='sophia.BlogTag'),
        ),
        migrations.AlterField(
            model_name='scheduledlesson',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Timeslot',
        ),
        migrations.AddField(
            model_name='scheduledlesson',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sophia.Student'),
            preserve_default=False,
        ),
    ]
