# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-16 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('sophia', '0010_auto_20161115_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledlesson',
            name='end_time',
            field=models.TimeField(default=datetime.datetime.now().time()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledlesson',
            name='start_time',
            field=models.TimeField(default=datetime.datetime.now().time()),
            preserve_default=False,
        ),
    ]
