# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-16 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sophia', '0011_auto_20161115_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledlesson',
            name='is_reschedule',
            field=models.BooleanField(default=False),
        ),
    ]
