# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-06-21 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import sophia.models


class Migration(migrations.Migration):

    dependencies = [
        ('sophia', '0012_scheduledlesson_is_reschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', sophia.models.SmartImageField(upload_to=b'./gallery_images/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('ordering', models.IntegerField(default=1)),
                ('priority', models.BooleanField(default=False, help_text=b'Determines if this image should be displayed on home screen')),
            ],
        ),
    ]
