# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-06-21 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sophia', '0013_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='tags',
            field=models.ManyToManyField(to='sophia.GalleryImageTag'),
        ),
    ]
